<template>
    <MovieGrid :movies="movies"/>
    <section>
        <h2>Remplissez le formulaire</h2>
        <form action="#">
            <label for="last-name">Nom</label>
            <input type="text" id="last-name" name="last-name" placeholder="Nom">
            <label for="first-name">Prénom</label>
            <input type="text" id="first-name" name="first-name" placeholder="Prénom">
            <label for="email">Adresse e-mail</label>
            <input type="email" id="email" name="email" placeholder="E-mail">
            <label for="city">Ville</label>
            <select name="city" id="city">
                <option value="paris">Paris</option>
                <option value="lyon">Lyon</option>
            </select>
            <label for="country">Pays</label>
            <select name="country" id="country">
                <option value="fr">France</option>
                <option value="en">Angleterre</option>
            </select>
            <input type="submit" value="Valider">
        </form>
    </section>
</template>

<script>
    import MovieGrid from "../components/MovieGrid.vue"

    export default {
        components: {
            MovieGrid
        },
        data() {
            return {
                movies: []
            }
        },
        async created() {
            // temporaire
            const response = await fetch("https://api.themoviedb.org/3/trending/all/day?api_key=cfd28171c3e2ccd8fdb64b5a8e13a97d")
            const data = await response.json()
            this.movies = data.results.slice(15, 20)
        }
    }
</script>

<style>
    section {
        background-color: var(--secondary-color);
        box-shadow: 0 .4rem .5rem rgba(0, 0, 0, 0.2);
        margin-top: 1.5rem;
        padding: 2rem;
    }

    section form {
        display: flex;
        flex-direction: column;
    }

    section h2 {
        color: #fff;
        text-align: center;
    }

    section form label {
        color: #fff;
        margin-top: 2rem;
        margin-bottom: .5rem;
    }

    section form input:not(input[type="submit"]) {
        line-height: 2.4rem;
        padding: .6rem 1.2rem;
        border-radius: 0.5rem;
    }

    section form select {
        height: 3.6rem;
        padding: .6rem;
        border-radius: 0.5rem;
    }

    section form input[type="submit"] {
        display: block;
        background-color: var(--tertiary-color);
        color: #222;
        padding: 1rem 3rem;
        margin: 0 auto;
        margin-top: 2rem;
        text-align: center;
        box-shadow: 0 .4rem .5rem rgba(0, 0, 0, 0.2);
        font-weight: bold;
        cursor: pointer;
    }

    @media only screen and (max-width: 767px) {
        main ul {
            grid-template-columns: repeat(1, 1fr);
            gap: 0;
            margin-bottom: 2rem;
        }

    }

    @media only screen and (min-width: 768px) and (max-width: 1024px) {
        main ul {
            grid-template-columns: repeat(3, 1fr);
        }
    }

    @media only screen and (max-width: 1024px) {
        main {
            margin: 2rem;
        }

        main ul {
            grid-template-rows: 1fr;
            grid-auto-rows: 0; /* set height to 0 for autogenerated grid rows */
            overflow-y: hidden;
        }

        main section {
            margin-top: 0;
        }
    }
</style>